import React from 'react'
import Head from 'next/head'

const About = () => {
    return (
        <>
        <Head>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <section>
                <h1>About page</h1>
            </section>
        </>
    )
}

export default About
