import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import App from '../public/main.jpg'
import partners from '../public/vercel.svg'
import hengst from '../public/hengst.svg'
import mann from '../public/mann.svg'
import hummel from '../public/mann-hummel.svg'
import fram from '../public/fram.svg'
import app from '../public/app.jpeg'

const About = () => {
    return (
        <>
        <Head>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <section className="relative block w-full h-auto bg-white max-w-screen-2xl mx-auto" id="aboutPage">
                {/* <header className="relative block w-full mx-auto">
                    <h4 className="text-center text-xs font-bold my-2 uppercase">Welcome to About page</h4>
                </header> */}
                <main className="relative w-full h-auto flex flex-col justify-center items-center">
                    <article className="relative w-full h-screen flex justify-center items-end bg-gray-200">
                        <div className="relative w-1/3 h-full overflow-hidden">
                            <Image src={App} layout="fill" sizes="100%"/>
                        </div>
                        <div className="relative flex flex-1 flex-col justify-center items-center h-full text-center px-4 pt-4  bg-opacity-75">
                            <div className="relative flex justify-start items-start text-left mb-10 divide-x-4 divide-solid divide-black">
                                <h2 className="text-5xl font-bold w-1/3 text-center ">About us</h2>
                                <p className="text-base w-2/3 pl-2">
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate, enim quae facere illo in incidunt. Consequuntur odio rem dolorum delectus!
                                    Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers. Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers.
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate, enim quae facere illo in incidunt. Consequuntur odio rem dolorum delectus!
                                    Getting a new business off the ground is a lot of hard work. Here are five ideas you can use
                                </p>
                            </div>
                            {/* <div className="relative flex justify-start items-start text-left  w-full">
                                <p className="text-lg w-4/5">
                                    Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers. Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers.
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate, enim quae facere illo in incidunt. Consequuntur odio rem dolorum delectus!
                                    Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers. Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers.
                                </p>
                            </div> */}
                        </div>
                    </article>
                    <article className="w-1/2 h-auto bg-white bg-opacity-50 -mt-48 relative flex flex-col justify-center items-start px-4 py-6 mb-6 shadow-md">
                        <div className="relative w-2/3 max-w-screen-lg ml-3 ">
                            <h1 className="relative font-bold text-3xl py-6 w-3/2">Our values</h1>
                        </div>
                        <div className="relative w-full h-auto flex justify-center items-center  max-w-screen-lg mx-auto ">
                            <ul className=" w-full h-auto flex justify-start items-center flex-wrap">
                                <li className="relative flex-col justify-center items-center w-1/2  px-2 py-1">
                                    <div>
                                        <Image src={partners} width={40} height={40}/>
                                    </div>
                                    <h2 className="font-bold text-lg">24/7 support</h2>
                                    <p className="text-md">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos, dignissimos?</p>
                                </li>
                                <li className="relative flex-col justify-center items-center w-1/2  px-2 py-1">
                                    <div>
                                        <Image src={hummel} width={40} height={40}/>
                                    </div>
                                    <h2 className="font-bold text-lg">24/7 support</h2>
                                    <p className="text-md">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos, dignissimos?</p>
                                </li>
                                <li className="relative flex-col justify-center items-center w-1/2  px-2 py-1">
                                    <div>
                                        <Image src={fram} width={40} height={40}/>
                                    </div>
                                    <h2 className="font-bold text-lg">24/7 support</h2>
                                    <p className="text-md">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos, dignissimos?</p>
                                </li>
                                <li className="relative flex-col justify-center items-center w-1/2  px-2 py-1">
                                    <div>
                                        <Image src={hengst} width={40} height={40}/>
                                    </div>
                                    <h2 className="font-bold text-lg">24/7 support</h2>
                                    <p className="text-md">Lorem ipsum dolor sit, amet consectetur adipisicing elit. Eos, dignissimos?</p>
                                </li>
                            </ul>
                            {/* <div className="relative block w-1/2 h-full px-2  overflow-hidden">
                                <Image src={app}  layout="responsive" objectFit="cover" sizes="100%" className="rounded-md"/>
                            </div> */}
                        </div>
                    </article>
                    <article className="relative w-full h-auto max-w-screen-xl mx-auto flex justify-center items-center py-8 " id="partners">
                        <div className="relative w-1/3 p-2 divide-x-4 divide-solid divide-black ">
                            <h1 className="font-bold text-3xl py-4">We are</h1>
                            <p className="pl-14 text-md w-2/3">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, nobis!</p>
                        </div>
                        <ul className="relative w-2/3 h-full flex flex-1 justify-start items-start flex-wrap ">
                            <li className="relative w-1/5 border-2  m-1 border-gray-400 rounded-lg p-2">
                                <p className="text-sm">Established in</p>
                                <h2 className="relative text-xl">2000</h2>
                            </li>
                            <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <p className="text-sm">Established in</p>
                                <h2 className="relative text-xl">2000</h2>
                            </li>
                            <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <p className="text-sm">Established in</p>
                                <h2 className="relative text-xl">2000</h2>
                            </li>
                            <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <p className="text-sm">Established in</p>
                                <h2 className="relative text-xl">2000</h2>
                            </li>
                            {/* <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <Image src={fram} width="70" height="70" layout="responsive"/>
                            </li>
                            <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <Image src={partners} width="70" height="70" layout="responsive"/>
                            </li> */}
                        </ul>
                    </article>
                    
                    <article className="relative w-full h-auto max-w-screen-xl mx-auto flex justify-center items-start py-8" id="partners">
                        <div className="relative w-1/3 p-2 divide-x-4 divide-solid divide-black ">
                            <h1 className="font-bold text-3xl py-4">Our partners</h1>
                            <p className="pl-14 text-md w-2/3">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, nobis!</p>
                        </div>
                        <ul className="relative w-2/3 h-full flex flex-1 justify-start items-start flex-wrap ">
                            <li className="relative w-1/5 border-2  m-1 border-gray-400 rounded-lg p-2">
                                <Image src={partners} width="70" height="70" layout="responsive"/>
                            </li>
                            <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <Image src={mann} width="70" height="70" layout="responsive"/>
                            </li>
                            <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <Image src={hengst} width="70" height="70" layout="responsive"/>
                            </li>
                            <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <Image src={hummel} width="70" height="70" layout="responsive"/>
                            </li>
                            <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <Image src={fram} width="70" height="70" layout="responsive"/>
                            </li>
                            <li className="relative w-1/5 m-1 border-2 border-gray-400 rounded-lg p-2">
                                <Image src={partners} width="70" height="70" layout="responsive"/>
                            </li>
                        </ul>
                    </article>
                </main>
            </section>
        </>
    )
}

export default About
