import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import App from '../public/main.jpg'
import partners from '../public/vercel.svg'

const About = () => {
    return (
        <>
        <Head>
            <title>About</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <section className="relative block w-full h-auto bg-blue-200" id="aboutPage">
                {/* <header className="relative block w-full mx-auto">
                    <h4 className="text-center text-xs font-bold my-2 uppercase">Welcome to About page</h4>
                </header> */}
                <main className="relative w-full h-auto flex flex-col justify-center items-center">
                    <article className="relative w-full h-screen flex justify-center items-end">
                        <div className="relative w-1/3 h-full overflow-hidden">
                            <Image src={App} layout="fill" sizes="100%"/>
                        </div>
                        <div className="relative flex flex-1 flex-col justify-center items-center h-full text-center px-6 pt-4 bg-green-100 bg-opacity-75">
                            <div className="relative flex justify-center items-start text-left mb-6">
                                <h2 className="text-4xl font-bold w-1/3 divide-x-2 divide-solid divide-black">About us</h2>
                                <p className="text-base w-2/4">
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate, enim quae facere illo in incidunt. Consequuntur odio rem dolorum delectus!
                                </p>
                            </div>
                            <div className="relative flex justify-center items-center text-left">
                                <p className="text-lg w-full">
                                    Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers. Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers.
                                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptate, enim quae facere illo in incidunt. Consequuntur odio rem dolorum delectus!
                                    Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers. Getting a new business off the ground is a lot of hard work. Here are five ideas you can use to find your first customers.
                                </p>
                            </div>
                        </div>
                    </article>
                    <article className="relative w-full h-auto max-w-screen-2xl mx-auto flex justify-center items-start bg-red-200" id="partners">
                        <div className="relative w-1/3 p-2 bg-red-500">
                            <h1 className="font-bold text-3xl py-4">Our partners</h1>
                            <p className="pl-10 text-lg w-2/3">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Voluptatum, nobis!</p>
                        </div>
                        <ul className="relative w-2/3 flex justify-around items-center flex-wrap bg-red-700">
                            <li className="relative w-1/4 m-1 bg-red-800">
                                <Image src={partners} width="100" height="100" layout="responsive"/>
                            </li>
                            <li className="relative w-1/4 m-1 bg-red-800">
                                <Image src={partners} width="100" height="100" layout="responsive"/>
                            </li>
                            <li className="relative w-1/4 m-1 bg-red-800">
                                <Image src={partners} width="100" height="100" layout="responsive"/>
                            </li>
                            <li className="relative w-1/4 m-1 bg-red-800">
                                <Image src={partners} width="100" height="100" layout="responsive"/>
                            </li>
                            <li className="relative w-1/4 m-1 bg-red-800">
                                <Image src={partners} width="100" height="100" layout="responsive"/>
                            </li>
                            <li className="relative w-1/4 m-1 bg-red-800">
                                <Image src={partners} width="100" height="100" layout="responsive"/>
                            </li>
                        </ul>
                    </article>
                </main>
            </section>
        </>
    )
}

export default About
