import React from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import Img from '../public/contactus.jpg'
import Fb from '../public/fb.svg'
import In from '../public/in.svg'

const Contacts = () => {
    return (
        <>
        <Head>
            <title>Contacts</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
            <section className="relative block w-full h-screen bg-gray-200">
                <main className="w-full h-full relative  max-w-screen-xl mx-auto flex flex-wrap justify-center items-center">
                    <article className="w-1/2 h-auto flex justify-start items-start flex-wrap">
                        <div className="relative w-full h-auto flex justify-start items-center flex-wrap mb-6">
                            <h1 className="relative block text-5xl font-bold w-full mb-6">Contact us</h1>
                            <p className="w-full relative block text-lg italic">Thanks for your interest in Megafil. Let's get in touch</p>
                        </div>
                        <div className="w-full h-auto  flex flex-col justify-center items-start mb-4">
                            <h1  className="font-bold text-lg py-1">Address</h1>
                            <div>
                                <h3 className="text-base">Ashgabat city, Parahat 2, Imperial Business Center, 7 floor, Room 1</h3>
                            </div>
                        </div>
                        {/* <div className="w-2/3 h-full relative">
                            <Image src={Img} sizes="100%" layout="fill"/>
                        </div> */}
                        <div className="w-full h-auto  flex flex-col justify-center items-start mb-4">
                            <h1  className="font-bold text-lg py-1">Info</h1>
                            <div>
                                <h3>Phone: +9931223-34-45</h3>
                                <h3>Email: info@megafil.com</h3>
                            </div>
                        </div>
                        <div className="w-full h-auto  flex flex-col justify-center items-start mb-4">
                            <h1  className="font-bold text-lg py-1">Open hours</h1>
                            <div>
                                <h3>Monday - Friday</h3>
                                <h3>9am - 17pm</h3>
                            </div>
                        </div>
                        <div className="w-full h-auto  flex flex-col justify-center items-start">
                            <h1  className="font-bold text-lg py-1">Follow us on socials</h1>
                            <div className="relative flex justify-between items-center">
                                <Link href="#">
                                    <a className="relative block mr-2">
                                        <Image src={Fb} width={30} height={30}/>
                                    </a>
                                </Link>
                                <Link href="#">
                                    <a className="relative block">
                                        <Image src={In} width={30} height={30}/>
                                    </a>
                                </Link>
                            </div>
                        </div>
                    </article>
                    <div className="relative w-1/2 h-full ">
                        <Image src={Img} layout="fill" sizes="100%" width={500} height={380}/> 
                    </div>
                </main>
            </section>
        </>
    )
}

export default Contacts
